import styles from '@/styles/Home.module.scss'
import { Container, Divider, useMediaQuery } from '@mui/material';
import Head from 'next/head';
import { useEffect, useState } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import Aside from '../../components/organisms/aside';
import Header from '../../components/organisms/header';
import ModalUsuarioTemplate from '../../components/organisms/modal-usuario';
import { openMobileMenuReducer } from '../../features/redux/mobile-menu-slice';
import HamburguerMenu from '../../components/icon-menu-mobile';
import DashboardVeiculos from '../../components/dashboard-veiculos';
import DashboardAbastecimentos from '../../components/dashboard-abastecimentos';
import ModalCadastro from '../../components/organisms/modal-cadastro';


export default function Home() {
  const [dashboardVeiculos, setDashboardVeiculos] = useState(false);
  const [dashboardAbastecimentos, setDashboardAbastecimentos] = useState(false);
  const [windowReady, setWindowReady] = useState(false);
  const modalLoginIsOpen = useSelector((state: any) => state.modal.modalLogin);
  const modalCadastroIsOpen = useSelector((state: any) => state.modal.modalCadastro);
  const showMobileMenu = useSelector((state: any) => state.mobileMenu.isOpen);
  const modalCadastroVeiculo = useSelector((state: any) => state.modal.modalCadastroVeiculo);
  const isMobile = useMediaQuery('(max-width:600px)');
  const dispatch = useDispatch();

  useEffect(() => {
    setWindowReady(true)
  }, [])


  useEffect(() => {
    if (!isMobile) {
      dispatch(openMobileMenuReducer())
    }
  }, [windowReady, isMobile]);

  return (
    <>
      <Head>
        <title>Abastecimento App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>

        {isMobile && !showMobileMenu && <HamburguerMenu />}
        {showMobileMenu && <Aside />}

        <Container className={styles.container}>

          <Header />

          <h1 className={styles.title}>Dashboard Geral</h1>

          <Divider />

          <span className={styles.listar}
            onClick={() => setDashboardVeiculos(!dashboardVeiculos)}>
            Listar Veiculos <span>{dashboardVeiculos ? "-" : "+"}</span>
          </span>

          {dashboardVeiculos && <DashboardVeiculos />}

          <Divider />

          <span className={styles.listar}
            onClick={() => setDashboardAbastecimentos(!dashboardAbastecimentos)}>
            Listar Abastecimentos <span>{dashboardAbastecimentos ? "-" : "+"}</span>
          </span>

          {dashboardAbastecimentos && <DashboardAbastecimentos />}
          <ModalCadastro isOpen={modalCadastroVeiculo} type='cadastroVeiculo'/>
          
        </Container>

      </main>


      {modalLoginIsOpen && <ModalUsuarioTemplate type="login" isOpen={modalLoginIsOpen} />}
      {modalCadastroIsOpen && <ModalUsuarioTemplate type="cadastro" isOpen={modalCadastroIsOpen} />}

    </>
  )
}
